### ISSUE TITLE
Error 420: Not being able to properly open the game

### ISSUE THREAD

**Issue by gombk** [lgpinguim/UnrealStudies#1]
I've been trying to open the game for a while now and this error always hit me. I think it's due that I'm not part of the red nation.
Could y'all look this up for me? Really want to play this game for a while

Pls fix

**Comment by lgpinguim** [comment]
The problem probably is happening because you lack the C++ runtime libraries necessary to run the game, I'm still looking for the correct way to create an installer with those, but at the moment you can try to download the following package from MS https://aka.ms/vs/16/release/vc_redist.x86.exe.
